### ISSUE TITLE
PnR links in transfers_ft.txt

### ISSUE THREAD

**Issue by dantischler** [osplanning-data-standards/GTFS-PLUS#1]
I see that access between PnR lots and stations is now in transfers_ft.txt, not transfers.txt. That solves the GTFS validation question, but it raises at least one new question. Currently, from_route_id and to_route_id are required in transfers_ft.txt, but at least one of these values should be null for PnR lots, and preferably both should be null. If both are null you establish access between PnR lot and station. If one is null you establish access between PnR lot and a route. The latter would require far more entries and would not add any obvious value.

Requested change - Allow null value or alternative non-route indicator for  from_route_id and to_route_id when specifying access between stations and PnR or KnR.

**Comment by e-lo** [comment]
@dantischler I see your point.  
@stefancoe or @lmz do you see any reason why we would require:
`from_route_id` 
`to_route_id` ?

https://github.com/osplanning-data-standards/GTFS-PLUS/blob/master/files/transfers_ft.md

**Comment by lmz** [comment]
I think it makes sense that these can be null.  I think it makes sense to be null in more situations than pnr/knr even... I would think that would be the normal case.  Why would there be route-specific transfer  attributes?

And related to this, I'm confused about the purpose of the schedule_precedence attribute, what does that mean and what's it for?

**Comment by lmz** [comment]
Also I would request that the docs could have some extra detail to make the relationship with the transfers.txt file more clear -- e.g. this _ft file is unique in that it contains a superset of the transfers in transfers.txt, since that file has no information about PNRs and KNRs.  AFAIK no other _ft.txt files are supsersets of their corresponding GTFS file plus other things.

**Comment by stefancoe** [comment]
Hi Lisa,
We want to be able to represent timed transfers between specific routes,
e.g. a feeder bus and a commuter rail line, and the GTFS specification does
not have a way to do this. Transfers.txt only handles transfers at a stop
level, so the transfer rule applies to all routes that serve the From and
To stop. Transfers_ft is an attempt to deal with this. In order to schedule
the timing of the two routes, one of the routes needs to be flexible so
it's schedule can be adjusted to make the transfer happen, which is what
schedule_precedence does.  This is most useful when creating a synthetic
schedule- we can schedule the route that takes precedence and then schedule
the other route so that it arrives at the transfer stop in time for the
transfer to be feasible. I was not considering the use of transfers_ft for
pnr/knr when we designed it, but if it works all the better. Thanks,

Stefan

**Comment by lmz** [comment]
Thanks, @stefancoe.  Most transfers aren't timed; are route ids only required for timed transfers?

With the schedule_precedence and timed transfers, does that mean that fasttrips is meant to make sure the schedule is adjusted (overriding stoptimes) so transfers could be made?  Or is that done upstream so fasttrips doesn't need to deal with this, and it's just informational?

**Comment by stefancoe** [comment]
When I designed this I was only thinking about timed transfers from a
scheduling perspective and we never decided whether fast-trips would
enforce the transfer or not. I have to plead ignorance here- it did not
occur to me that this file would represent all feasible transfers for
fast-trips, but i guess this make sense. Now I see that transfers.txt was
represented as ft_input_transfers.dat in the old version and was used to
represent all transfers so it makes even more sense (my recollection was
this was a non GTFS input, similar to ft_input_accessLinks.dat) . So given
that, yes, route ids should only be required for timed transfers.

**Comment by e-lo** [comment]
@lmz , let's talk about the following in real time:
1. Should FT create the majority of xfers given a set of rules or should it be fed them all?
2. Given answer to above, what is most efficient way to represent a timed xfer if one exists [ this is mainly for shuttles to/from Caltrain and similar...we don't want the last one to leave before the train gets there b/c that will create havoc ]

**Comment by e-lo** [comment]
Talked with @lmz   ---  decided to keep xfer creation separate from FT and in the network creation process.  

Will make change to specification for `transfers_ft.txt` to clarify that there can be null values.
