### ISSUE TITLE
null columns in transfers_ft.txt

### ISSUE THREAD

**Issue by bhargavasana** [osplanning-data-standards/GTFS-PLUS#15]
Could someone please explain this statement in description for from_stop_id/to_stop_id columns?
"Can be null if a drive access point (KNR/PNR)."

What would null value mean?

PS: @e-lo - I am not able to apply labels to issues. Do I need permission?

**Comment by e-lo** [comment]
- I'll add you as an admin to this project - you can't add labels otherwise [ i guess they don't want the public to add a "must fix" to any old project ]
- null is just blank.  It was added per: https://github.com/osplanning-data-standards/GTFS-PLUS/issues/1

...but if there is something wrong with this then let's fix it!

**Comment by bhargavasana** [comment]
@e-lo - it appears that as per #1 from_route_id and to_route_id could be null; from_stop_id and to_stop_id should still be non-null?

**Comment by e-lo** [comment]
@bhargavasana  - sorry about that, I misread your original issue!  This appears to be an [error that I introduced](https://github.com/osplanning-data-standards/GTFS-PLUS/commit/f3fdb0cb8a4d8dd5e2981a91ed8264e5939a339b) when I fixed #1 so I'll revert back.
