### ISSUE TITLE
Update for removal of fare_class from routes_ft

### ISSUE THREAD

**Issue by lmz** [osplanning-data-standards/GTFS-PLUS#22]
fare_routes_ft.md mentions fare_class with respect to routes_ft.txt, but fare_class was removed from routes_ft.txt

Also the fare documentation (fares.md) has examples with fare_class in routes_ft as well

As an aside, I find fare_class a little confusing since it's really a time bounded fare_id, right?  So I like fare_period_id or something like that better, personally.

**Comment by e-lo** [comment]
This is really three issues
1. [proposed renaming of a variable](https://github.com/osplanning-data-standards/GTFS-PLUS/issues/23)
2. [bug in specification](https://github.com/osplanning-data-standards/GTFS-PLUS/issues/24) 
3. [updating of documentation. That whole section is out of date really. ](https://github.com/osplanning-data-standards/GTFS-PLUS/issues/25)

I'll create separate ones since they might be resolved at different times.
